In [1]:
import numpy as np
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [2]:
type(test_array[3])

numpy.float64

In [3]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [4]:
print(type(test_array[3])) # 실수형(floating Type)으로 자동 형 변환 실시

<class 'numpy.float64'>


In [5]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환

float64


In [6]:
print(test_array.shape) # 배열의 구조(shape)를 반환함

(4,)


In [7]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape
# 앞의 값이 행(row), 뒤의 값이 열(column)

(3, 4)

In [9]:
tensor_rank3 = [
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
]
np.array(tensor_rank3, int).shape
# 실수하기 좋은 예제

(4, 3, 4)

In [10]:
tensor_rank3 = [[[1,2,5,8], [1,2,5,8], [1,2,5,8]], [[1,2,5,8], [1,2,5,8], [1,2,5,8]], [[1,2,5,8], [1,2,5,8], [1,2,5,8]], [[1,2,5,8], [1,2,5,8], [1,2,5,8]]]
np.array(tensor_rank3, int).ndim

3

In [11]:
np.array(tensor_rank3, int).size

48

In [12]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=int) # 정수형

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=float) # 실수형

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [14]:
import sys

np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float64).itemsize

8

In [15]:
np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float32).itemsize

4

In [17]:
x = np.array([[1,2,5,8], [1,2,5,8]])
x.shape

(2, 4)

In [18]:
x.reshape(-1, )

array([1, 2, 5, 8, 1, 2, 5, 8])

In [19]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [22]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
x.flatten() # 1차원으로 변경해주는 함수

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
x = np.array([[1,2,3],[4.5,5,6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x[0][0]

1

In [30]:
x[0,2]

3

In [31]:
x[0,1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [40]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]],int)
x[:, 2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [41]:
x[1, 1 : 3] # 1행의 1열~2열

array([7, 8])

In [42]:
x[1 : 3] # 1행~2행의 전체

array([[ 6,  7,  8,  9, 10]])

In [35]:
x = np.array(range(15),int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
x[:, ::2] # 시작부터 2씩 증가

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [37]:
x[::2, ::3] # 시작부터 끝까지 2씩 증가, 시작부터 끝까지 3씩 증가

array([[ 0,  3],
       [10, 13]])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [45]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [46]:
np.ones(shape=(5, 2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [48]:
np.zeros(shape=(2, 2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [50]:
np.empty(shape=(2,4), dtype=np.float32)

array([[0.    , 1.875 , 0.    , 2.25  ],
       [0.    , 2.3125, 0.    , 2.5   ]], dtype=float32)

In [51]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [53]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [61]:
np.empty_like(x)

array([[                  0,                  50,                   0,
                          0],
       [       150323855360, 3543889139687646571, 3257572794014708018,
        7149521777190844774],
       [3687657775223156025, 3474587827804977506, 8386112019188953446,
        9023020265967350645]])

In [54]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [56]:
np.eye(N=3, M=5) # N = row, M = column

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [58]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
np.diag(matrix)

array([0, 4, 8])

In [62]:
np.diag(matrix, k = 1)

array([1, 5])

In [63]:
np.random.uniform(0,5,10)

array([0.3979331 , 2.31654289, 1.76833268, 4.58262274, 1.17013568,
       1.9811861 , 0.8125519 , 4.05736545, 2.673209  , 4.10554505])

In [64]:
np.random.normal(0,2,10)

array([ 1.64018082,  1.77919117, -1.02634214, -1.25201664,  3.77147949,
       -2.30023736,  1.79386413, -2.59437483,  1.88844019, -0.62296058])

In [65]:
import numpy as np
test_array = np.arange(1, 11)
test_array.sum()

55

In [66]:
test_array = np.arange(1, 13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
test_array.sum(axis = 0)

array([15, 18, 21, 24])

In [68]:
test_array.sum(axis=1)

array([10, 26, 42])

In [70]:
test_array = np.arange(1,13).reshape(3,4)

third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [71]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [72]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [73]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [74]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
test_array.mean(axis=1) # axis=1 축을 기준으로 평균 연산

array([ 2.5,  6.5, 10.5])

In [76]:
test_array.std() # 전체 값에 대한 표준편차 연산

3.452052529534663

In [77]:
test_array.std(axis=0) # axis=0 축을 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [79]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [80]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [82]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [83]:
v2

array([[4],
       [5],
       [6]])

In [84]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [87]:
v2

array([[5],
       [6]])

In [89]:
np.concatenate((v1,v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [91]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [93]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [99]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [94]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [96]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [100]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [102]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [103]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [104]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [105]:
x = np.arange(1, 13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [106]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [107]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [108]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [109]:
import numpy as np
x = np.array([4,3,2,6,8,5])
x > 3

array([ True, False, False,  True,  True,  True])

In [111]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x > y

array([False,  True, False])

In [112]:
x = np.array([4,6,7,3,2])
(x > 3)

array([ True,  True,  True, False, False])

In [113]:
(x > 3).all()

False

In [114]:
(x > 3).any()

True

In [115]:
(x < 10).any()

True

In [116]:
(x < 10).all()

True

In [117]:
(x > 10).any()

False

In [118]:
x = np.array([4,6,7,3,2])
x > 5

array([False,  True,  True, False, False])

In [120]:
np.where(x>5)

(array([1, 2]),)

In [121]:
x = np.array([4,6,7,3,2])
np.where(x>5, 10, 20)

array([20, 10, 10, 20, 20])

In [122]:
x = np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [124]:
np.argmax(x)

2

In [125]:
np.argmin(x)

4

In [126]:
x = np.array([4,6,7,3,2])
x > 3

array([ True,  True,  True, False, False])

In [127]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [128]:
x.shape

(5,)

In [129]:
cond.shape

(5,)

In [133]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2,], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [135]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [136]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0,1,1,1,0,0], int)
b = np.array([0,0,0,1,1,1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])